<?php

namespace AppBundle\Repository;

/**
 * ClueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClueRepository extends \Doctrine\ORM\EntityRepository
{
}
