<?php

namespace AppBundle\Repository;

/**
 * KillerCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KillerCardRepository extends \Doctrine\ORM\EntityRepository
{
}
