<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Party;

/**
 * TrialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrialRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCurrentTrials(Party $party)
    {
        $query = $this->createQueryBuilder('trial');
        $query
            ->join('trial.contract', 'contract')
            ->join('contract.owner', 'owner')
            ->where($query->expr()->eq('trial.completed', ':completed'))
            ->andWhere($query->expr()->eq('owner.party', ':party'));
        return $query
            ->setParameter('completed', false)
            ->setParameter('party', $party)
            ->getQuery()->getResult()
        ;
    }
}
